### ISSUE TITLE
Wordpress Enqueuing is not working anymore

### ISSUE THREAD

**Issue by fabianhenzler** [intercom/intercom-wordpress#82]
```PHP Fatal error: Uncaught Error: Cannot access empty property in /public_html/wp-content/plugins/intercom/bootstrap.php:18
Stack trace:
#0 /public_html/wp-content/plugins/intercom/bootstrap.php(353): IdentityVerificationCalculator->__construct(Array, 'xxxxxx...', '')
#1 /wp-content/plugins/intercom/bootstrap.php(342): IntercomSnippetSettings->getRawData()
#2 /wp-content/plugins/intercom/bootstrap.php(317): IntercomSnippetSettings->json()
#3 /wp-content/plugins/intercom/bootstrap.php(296): IntercomSnippet->source()
#4 /wp-content/plugins/intercom/bootstrap.php(459): IntercomSnippet->html()
#5 /wp-includes/class-wp-hook.php(298): add_intercom_s in /wp-content/plugins/intercom/bootstrap.php on line 18```

**Comment by Skaelv** [comment]
Hey @fabianhenzler ! Which version of the plugin are you using ?

**Comment by fabianhenzler** [comment]
Hi @Skaelv :) I'm using the most recent one 2.5.11

**Comment by fabianhenzler** [comment]
Our infrastructure support just confirmed - everything works when the plugin version 2.5.11 is disabled

**Comment by Skaelv** [comment]
Thanks for reporting this issue. A fix should be released pretty soon in `v2.5.12`

**Comment by Skaelv** [comment]
`2.5.12` was just released with a fix for your issue. I'm closing this issue. Try to upgrade and reopen if the issue persist or if you run into another issue.

**Comment by fabianhenzler** [comment]
Updated, but same error
```
[14-Apr-2017 13:25:58 UTC] PHP Fatal error:  Uncaught Error: Cannot access empty property in /wp-content/plugins/intercom/bootstrap.php:20
Stack trace:
#0 /wp-content/plugins/intercom/bootstrap.php(399): IdentityVerificationCalculator->__construct(Array, 'cvyIO0ByJX_PV7n...', '')
#1 /wp-content/plugins/intercom/bootstrap.php(386): IntercomSnippetSettings->getRawData()
#2 /wp-content/plugins/intercom/bootstrap.php(357): IntercomSnippetSettings->json()
#3 /wp-content/plugins/intercom/bootstrap.php(333): IntercomSnippet->source()
#4 /wp-content/plugins/intercom/bootstrap.php(519): IntercomSnippet->html()
#5 /wp-includes/class-wp-hook.php(298): add_intercom_s in /wp-content/plugins/intercom/bootstrap.php on line 20
```

**Comment by Skaelv** [comment]
Ok I only fixed the admin page in the previous release. [This PR](https://github.com/intercom/intercom-wordpress/pull/84) will fix your issue. I'll let you know when `2.5.13` is released.

**Comment by Skaelv** [comment]
Just released the new version :crossed_fingers:  Let me know :)

**Comment by fabianhenzler** [comment]
```
PHP Fatal error: Uncaught Error: Cannot access empty property in /wp-content/plugins/intercom/bootstrap.php:20
Stack trace:
#0 /wp-content/plugins/intercom/bootstrap.php(399): IdentityVerificationCalculator->__construct(Array, 'xxx...', '')
#1 /wp-content/plugins/intercom/bootstrap.php(386): IntercomSnippetSettings->getRawData()
#2 /wp-content/plugins/intercom/bootstrap.php(357): IntercomSnippetSettings->json()
#3 /wp-content/plugins/intercom/bootstrap.php(333): IntercomSnippet->source()
#4 /wp-content/plugins/intercom/bootstrap.php(520): IntercomSnippet->html()
#5 /wp-includes/class-wp-hook.php(298): add_intercom_s in /wp-content/plugins/intercom/bootstrap.php on line 20
```

2.5.13 - Sadly no change :(

**Comment by Skaelv** [comment]
Hey I'm not going to be able to fix that now so you better just revert back to `2.5.10` until we fix it for real. Thanks for your patience

**Comment by fabianhenzler** [comment]
ok :( where will I get that version? the repo has no tags

**Comment by fabianhenzler** [comment]
https://plugins.trac.wordpress.org/browser/intercom/trunk/bootstrap.php?rev=1629079

**Comment by Skaelv** [comment]
The new release of `v2.5.14` fixes the issue @fabianhenzler .
